// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsEmbeddedUI(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashEmbeddedUI(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsEmbeddedUI(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsEmbeddedUI(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsEmbeddedUI(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsEmbeddedUI(lhsKey, rhsKey) {
          if deepEqualsEmbeddedUI(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsEmbeddedUI(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashEmbeddedUI(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashEmbeddedUI(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashEmbeddedUI(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashEmbeddedUI(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashEmbeddedUI(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashEmbeddedUI(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Generated class from Pigeon that represents data sent in messages.
struct TimelineBucket: Hashable {
  var offset: Int64
  var count: Int64
  var epochMilliseconds: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TimelineBucket? {
    let offset = pigeonVar_list[0] as! Int64
    let count = pigeonVar_list[1] as! Int64
    let epochMilliseconds: Int64? = nilOrValue(pigeonVar_list[2])

    return TimelineBucket(
      offset: offset,
      count: count,
      epochMilliseconds: epochMilliseconds
    )
  }
  func toList() -> [Any?] {
    return [
      offset,
      count,
      epochMilliseconds,
    ]
  }
  static func == (lhs: TimelineBucket, rhs: TimelineBucket) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsEmbeddedUI(lhs.offset, rhs.offset) && deepEqualsEmbeddedUI(lhs.count, rhs.count) && deepEqualsEmbeddedUI(lhs.epochMilliseconds, rhs.epochMilliseconds)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TimelineBucket")
    deepHashEmbeddedUI(value: offset, hasher: &hasher)
    deepHashEmbeddedUI(value: count, hasher: &hasher)
    deepHashEmbeddedUI(value: epochMilliseconds, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AssetMeta: Hashable {
  var id: String
  var remoteId: String? = nil
  var localId: String? = nil
  var createdAtEpochMilliseconds: Int64
  var isFavorite: Bool
  var isVideo: Bool
  var isEdited: Bool
  var thumbhash: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AssetMeta? {
    let id = pigeonVar_list[0] as! String
    let remoteId: String? = nilOrValue(pigeonVar_list[1])
    let localId: String? = nilOrValue(pigeonVar_list[2])
    let createdAtEpochMilliseconds = pigeonVar_list[3] as! Int64
    let isFavorite = pigeonVar_list[4] as! Bool
    let isVideo = pigeonVar_list[5] as! Bool
    let isEdited = pigeonVar_list[6] as! Bool
    let thumbhash: String? = nilOrValue(pigeonVar_list[7])

    return AssetMeta(
      id: id,
      remoteId: remoteId,
      localId: localId,
      createdAtEpochMilliseconds: createdAtEpochMilliseconds,
      isFavorite: isFavorite,
      isVideo: isVideo,
      isEdited: isEdited,
      thumbhash: thumbhash
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      remoteId,
      localId,
      createdAtEpochMilliseconds,
      isFavorite,
      isVideo,
      isEdited,
      thumbhash,
    ]
  }
  static func == (lhs: AssetMeta, rhs: AssetMeta) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsEmbeddedUI(lhs.id, rhs.id) && deepEqualsEmbeddedUI(lhs.remoteId, rhs.remoteId) && deepEqualsEmbeddedUI(lhs.localId, rhs.localId) && deepEqualsEmbeddedUI(lhs.createdAtEpochMilliseconds, rhs.createdAtEpochMilliseconds) && deepEqualsEmbeddedUI(lhs.isFavorite, rhs.isFavorite) && deepEqualsEmbeddedUI(lhs.isVideo, rhs.isVideo) && deepEqualsEmbeddedUI(lhs.isEdited, rhs.isEdited) && deepEqualsEmbeddedUI(lhs.thumbhash, rhs.thumbhash)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AssetMeta")
    deepHashEmbeddedUI(value: id, hasher: &hasher)
    deepHashEmbeddedUI(value: remoteId, hasher: &hasher)
    deepHashEmbeddedUI(value: localId, hasher: &hasher)
    deepHashEmbeddedUI(value: createdAtEpochMilliseconds, hasher: &hasher)
    deepHashEmbeddedUI(value: isFavorite, hasher: &hasher)
    deepHashEmbeddedUI(value: isVideo, hasher: &hasher)
    deepHashEmbeddedUI(value: isEdited, hasher: &hasher)
    deepHashEmbeddedUI(value: thumbhash, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ServerConfig: Hashable {
  var endpoint: String
  var token: String
  var customHeaders: [String: String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ServerConfig? {
    let endpoint = pigeonVar_list[0] as! String
    let token = pigeonVar_list[1] as! String
    let customHeaders = pigeonVar_list[2] as! [String: String]

    return ServerConfig(
      endpoint: endpoint,
      token: token,
      customHeaders: customHeaders
    )
  }
  func toList() -> [Any?] {
    return [
      endpoint,
      token,
      customHeaders,
    ]
  }
  static func == (lhs: ServerConfig, rhs: ServerConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsEmbeddedUI(lhs.endpoint, rhs.endpoint) && deepEqualsEmbeddedUI(lhs.token, rhs.token) && deepEqualsEmbeddedUI(lhs.customHeaders, rhs.customHeaders)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ServerConfig")
    deepHashEmbeddedUI(value: endpoint, hasher: &hasher)
    deepHashEmbeddedUI(value: token, hasher: &hasher)
    deepHashEmbeddedUI(value: customHeaders, hasher: &hasher)
  }
}

private class EmbeddedUIPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return TimelineBucket.fromList(self.readValue() as! [Any?])
    case 130:
      return AssetMeta.fromList(self.readValue() as! [Any?])
    case 131:
      return ServerConfig.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class EmbeddedUIPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? TimelineBucket {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? AssetMeta {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? ServerConfig {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class EmbeddedUIPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return EmbeddedUIPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return EmbeddedUIPigeonCodecWriter(data: data)
  }
}

class EmbeddedUIPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = EmbeddedUIPigeonCodec(readerWriter: EmbeddedUIPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol EmbeddedHostApi {
  func onFlutterReady() throws
  func onRequestPop() throws
  func onAuthChanged(isAuthenticated: Bool) throws
  func onRouteStateChanged(canPop: Bool, title: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class EmbeddedHostApiSetup {
  static var codec: FlutterStandardMessageCodec { EmbeddedUIPigeonCodec.shared }
  /// Sets up an instance of `EmbeddedHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: EmbeddedHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let onFlutterReadyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.EmbeddedHostApi.onFlutterReady\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onFlutterReadyChannel.setMessageHandler { _, reply in
        do {
          try api.onFlutterReady()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      onFlutterReadyChannel.setMessageHandler(nil)
    }
    let onRequestPopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.EmbeddedHostApi.onRequestPop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onRequestPopChannel.setMessageHandler { _, reply in
        do {
          try api.onRequestPop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      onRequestPopChannel.setMessageHandler(nil)
    }
    let onAuthChangedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.EmbeddedHostApi.onAuthChanged\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onAuthChangedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isAuthenticatedArg = args[0] as! Bool
        do {
          try api.onAuthChanged(isAuthenticated: isAuthenticatedArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      onAuthChangedChannel.setMessageHandler(nil)
    }
    let onRouteStateChangedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.EmbeddedHostApi.onRouteStateChanged\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onRouteStateChangedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let canPopArg = args[0] as! Bool
        let titleArg = args[1] as! String
        do {
          try api.onRouteStateChanged(canPop: canPopArg, title: titleArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      onRouteStateChangedChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol EmbeddedFlutterApiProtocol {
  func navigateTo(routeName routeNameArg: String, args argsArg: [String: Any?], completion: @escaping (Result<Void, PigeonError>) -> Void)
  func maybePop(completion: @escaping (Result<Bool, PigeonError>) -> Void)
  func setEmbeddedMode(hideChrome hideChromeArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func resetToRoot(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class EmbeddedFlutterApi: EmbeddedFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: EmbeddedUIPigeonCodec {
    return EmbeddedUIPigeonCodec.shared
  }
  func navigateTo(routeName routeNameArg: String, args argsArg: [String: Any?], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.immich_mobile.EmbeddedFlutterApi.navigateTo\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([routeNameArg, argsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func maybePop(completion: @escaping (Result<Bool, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.immich_mobile.EmbeddedFlutterApi.maybePop\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! Bool
        completion(.success(result))
      }
    }
  }
  func setEmbeddedMode(hideChrome hideChromeArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.immich_mobile.EmbeddedFlutterApi.setEmbeddedMode\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([hideChromeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func resetToRoot(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.immich_mobile.EmbeddedFlutterApi.resetToRoot\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TimelineHostApi {
  func onTimelineChanged() throws
  func onAssetsChanged(assetIds: [String]) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TimelineHostApiSetup {
  static var codec: FlutterStandardMessageCodec { EmbeddedUIPigeonCodec.shared }
  /// Sets up an instance of `TimelineHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TimelineHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let onTimelineChangedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.TimelineHostApi.onTimelineChanged\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onTimelineChangedChannel.setMessageHandler { _, reply in
        do {
          try api.onTimelineChanged()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      onTimelineChangedChannel.setMessageHandler(nil)
    }
    let onAssetsChangedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.immich_mobile.TimelineHostApi.onAssetsChanged\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onAssetsChangedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let assetIdsArg = args[0] as! [String]
        do {
          try api.onAssetsChanged(assetIds: assetIdsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      onAssetsChangedChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol TimelineFlutterApiProtocol {
  func loadBuckets(completion: @escaping (Result<[TimelineBucket], PigeonError>) -> Void)
  func loadAssets(offset offsetArg: Int64, count countArg: Int64, completion: @escaping (Result<[AssetMeta], PigeonError>) -> Void)
  func thumbnailUrl(assetId assetIdArg: String, thumbhash thumbhashArg: String?, edited editedArg: Bool, completion: @escaping (Result<String, PigeonError>) -> Void)
  func serverConfig(completion: @escaping (Result<ServerConfig, PigeonError>) -> Void)
  func setFavorite(ids idsArg: [String], value valueArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func delete(ids idsArg: [String], completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class TimelineFlutterApi: TimelineFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: EmbeddedUIPigeonCodec {
    return EmbeddedUIPigeonCodec.shared
  }
  func loadBuckets(completion: @escaping (Result<[TimelineBucket], PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.immich_mobile.TimelineFlutterApi.loadBuckets\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! [TimelineBucket]
        completion(.success(result))
      }
    }
  }
  func loadAssets(offset offsetArg: Int64, count countArg: Int64, completion: @escaping (Result<[AssetMeta], PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.immich_mobile.TimelineFlutterApi.loadAssets\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([offsetArg, countArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! [AssetMeta]
        completion(.success(result))
      }
    }
  }
  func thumbnailUrl(assetId assetIdArg: String, thumbhash thumbhashArg: String?, edited editedArg: Bool, completion: @escaping (Result<String, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.immich_mobile.TimelineFlutterApi.thumbnailUrl\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([assetIdArg, thumbhashArg, editedArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! String
        completion(.success(result))
      }
    }
  }
  func serverConfig(completion: @escaping (Result<ServerConfig, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.immich_mobile.TimelineFlutterApi.serverConfig\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! ServerConfig
        completion(.success(result))
      }
    }
  }
  func setFavorite(ids idsArg: [String], value valueArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.immich_mobile.TimelineFlutterApi.setFavorite\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([idsArg, valueArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func delete(ids idsArg: [String], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.immich_mobile.TimelineFlutterApi.delete\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([idsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
